//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.4.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>FrontSection</summary>
	[PublishedContentModel("frontSection")]
	public partial class FrontSection : PublishedContentModel, ISectionBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "frontSection";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FrontSection(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FrontSection, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// BigText
		///</summary>
		[ImplementPropertyType("bigText")]
		public string BigText
		{
			get { return this.GetPropertyValue<string>("bigText"); }
		}

		///<summary>
		/// BotText
		///</summary>
		[ImplementPropertyType("botText")]
		public string BotText
		{
			get { return this.GetPropertyValue<string>("botText"); }
		}

		///<summary>
		/// BackgroundImage
		///</summary>
		[ImplementPropertyType("backgroundImage")]
		public string BackgroundImage
		{
			get { return SectionBase.GetBackgroundImage(this); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public string Description
		{
			get { return SectionBase.GetDescription(this); }
		}

		///<summary>
		/// SectionMainText
		///</summary>
		[ImplementPropertyType("sectionMainText")]
		public string SectionMainText
		{
			get { return SectionBase.GetSectionMainText(this); }
		}

		///<summary>
		/// SectionName
		///</summary>
		[ImplementPropertyType("sectionName")]
		public string SectionName
		{
			get { return SectionBase.GetSectionName(this); }
		}
	}
}
