//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.4.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1085 with alias "sectionBase"
	/// <summary>SectionBase</summary>
	public partial interface ISectionBase : IPublishedContent
	{
		/// <summary>BackgroundImage</summary>
		string BackgroundImage { get; }

		/// <summary>Description</summary>
		string Description { get; }

		/// <summary>SectionMainText</summary>
		string SectionMainText { get; }

		/// <summary>SectionName</summary>
		string SectionName { get; }
	}

	/// <summary>SectionBase</summary>
	[PublishedContentModel("sectionBase")]
	public partial class SectionBase : PublishedContentModel, ISectionBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "sectionBase";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SectionBase(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SectionBase, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// BackgroundImage
		///</summary>
		[ImplementPropertyType("backgroundImage")]
		public string BackgroundImage
		{
			get { return GetBackgroundImage(this); }
		}

		/// <summary>Static getter for BackgroundImage</summary>
		public static string GetBackgroundImage(ISectionBase that) { return that.GetPropertyValue<string>("backgroundImage"); }

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public string Description
		{
			get { return GetDescription(this); }
		}

		/// <summary>Static getter for Description</summary>
		public static string GetDescription(ISectionBase that) { return that.GetPropertyValue<string>("description"); }

		///<summary>
		/// SectionMainText
		///</summary>
		[ImplementPropertyType("sectionMainText")]
		public string SectionMainText
		{
			get { return GetSectionMainText(this); }
		}

		/// <summary>Static getter for SectionMainText</summary>
		public static string GetSectionMainText(ISectionBase that) { return that.GetPropertyValue<string>("sectionMainText"); }

		///<summary>
		/// SectionName
		///</summary>
		[ImplementPropertyType("sectionName")]
		public string SectionName
		{
			get { return GetSectionName(this); }
		}

		/// <summary>Static getter for SectionName</summary>
		public static string GetSectionName(ISectionBase that) { return that.GetPropertyValue<string>("sectionName"); }
	}
}
