//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.4.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>TestimonialItem</summary>
	[PublishedContentModel("testimonialItem")]
	public partial class TestimonialItem : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "testimonialItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TestimonialItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TestimonialItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// OrginizationPosition
		///</summary>
		[ImplementPropertyType("orginizationPosition")]
		public string OrginizationPosition
		{
			get { return this.GetPropertyValue<string>("orginizationPosition"); }
		}

		///<summary>
		/// Photo
		///</summary>
		[ImplementPropertyType("photo")]
		public string Photo
		{
			get { return this.GetPropertyValue<string>("photo"); }
		}

		///<summary>
		/// TestimonialName
		///</summary>
		[ImplementPropertyType("testimonialName")]
		public string TestimonialName
		{
			get { return this.GetPropertyValue<string>("testimonialName"); }
		}

		///<summary>
		/// TestimonialText
		///</summary>
		[ImplementPropertyType("testimonialText")]
		public string TestimonialText
		{
			get { return this.GetPropertyValue<string>("testimonialText"); }
		}
	}
}
